name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: startsWith(runner.os, 'Linux')
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ ninja-build ccache

      - name: Install dependencies (macOS)
        if: startsWith(runner.os, 'macOS')
        run: |
          brew update
          brew install cmake ninja ccache

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: cmake --build build -j

      - name: Smoke test
        run: |
          ./build/latticedb < tests/smoke.sql
